### ISSUE TITLE
Forex currency pair prediction

### ISSUE THREAD

**Issue by ericleonardo** [pixelhero98/DGDNN#1]
Hi... Do you think DGDNN will work predicting direction of Forex data?
I would like to predict if EURUSD pair will go up or down next day.
Also, please will you share the ipynb version?
Congratulations for the great work! Thank you.

**Comment by pixelhero98** [comment]
Yes, we can modify the model to fit your purpose. I will release the .ipynb version in the following three months (annual leave now).

**Comment by ericleonardo** [comment]
Very good! Maybe we can explore the triangular arbitrage interaction (predict EURUSD based on EURUSD, GBPUSD, EURGBP) to see if it is beneficial to enhance prediction or not. Or find other relevant features to EURUSD beyond itself. Thank you!
