### ISSUE TITLE
Data labelling method is not clear

### ISSUE THREAD

**Issue by kwan-0915** [pixelhero98/DGDNN#2]
Dear authors, 

Hello, thanks for the work! 

I have a question which is related to how you label your data. 

In your paper, under equation 1, you use a look-back window which contain [t − τ + 1, t] information as input. I wonder how you label the output for time t. Can you give me an example? 

Thank you.

**Comment by pixelhero98** [comment]
Hi,

Please check the data generation file for details. E.g., on each trading day, the trend of the stock is labeled as 0 or 1 based on the close price difference between the current day and the previous day.

**Comment by kwan-0915** [comment]
> Hi,
> 
> Please check the data generation file for details. E.g., on each trading day, the trend of the stock is labeled as 0 or 1 based on the close price difference between the current day and the previous day.

Hello, thank you for your quick reply. 

According to your reply, I summarise as follow: label<sub>t</sub> = sign(close<sub>t</sub> - close<sub>t-1</sub>)

However, the input matrix includes information at time t, which are close<sub>t</sub> and close<sub>t-1</sub>, isn't it cheating or look-ahead? 

If the label<sub>t</sub> is created base on close<sub>t</sub> and close<sub>t-1</sub>, and we need both of them as an input to "predict" the label<sub>t</sub>, why don't we just subtract close<sub>t</sub> and close<sub>t-1</sub>? 

I have drawn a pic to illustrate my question, hope this can give you a clear view of my question. 

I am new to this topic, my question may be stupid to you, if possible, please give me an example, what exactly we are predicting at time<sub>t</sub>, thank you!

![unnamed](https://github.com/pixelhero98/DGDNN/assets/43068473/f117e0cd-d987-465f-8ca3-b63353c631e9)

**Comment by pixelhero98** [comment]
the mapping is always current→next (t→t+1, in your case, should be t-1→t, your observation point is t-1), so in the val or test set, say day k, we want to predict k+1 we use features from [t-\tau+1, t]. The label of k+1 depends on both c_k+1 and c_k, so all the model has to learn is necessarily the actual c_k+1, hence it is not looking ahead.

**Comment by kwan-0915** [comment]
> the mapping is always current→next (t→t+1, in your case, should be t-1→t, your observation point is t-1), so in the val or test set, say day k, we want to predict k+1 we use features from [k-\tau+1, k]. The label of k+1 depends on both c_k+1 and c_k, so all the model has to learn to predict is necessarily the actual c_k+1, hence it is not looking ahead.

Thank you for you reply. So if I understand correctly, at time t (the current time) we are actually predicting the label y<sub>t+1</sub> but not y<sub>t</sub>, and due to the fact that y<sub>t+1</sub> is computed by both close<sub>t+1</sub> and close<sub>t</sub>, hence no look-ahead.  Is this what you mean?

I will take a look on the code, once again, thank you for your help, hope you have a nice day.

**Comment by pixelhero98** [comment]
Yes. It's always the case using the past and present to predict the future.
